server:
  port: 8080
  servlet:
    context-path: /community

spring:
  # 后来发现的 bean 会覆盖之前相同名称的 bean
  # main:
    # allow-bean-definition-overriding: true
  # 数据库连接相关信息
  datasource:
    url: jdbc:mysql://localhost:3306/community?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    # 连接池的类型、最大连接数、最小保留数、关闭超
    # 该连接池的类型标注为 HikariDataSource ，该类型是一个第三方的包，并不是 Mybatis 自带的类型
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      idle-timeout: 30000
  # thymeleaf 的缓存设置为关闭
  thymeleaf:
    cache: false
  # 邮箱相关参数配置
  # 接收邮件服务器：imap.qq.com，使用 SSL，端口号993
  # 发送邮件服务器：smtp.qq.com，使用 SSL，端口号465或587
  mail:
    host: smtp.qq.com
    port: 465
    username: swrely@qq.com
    password: nkphtzkshprpdidj
    protocol: smtps
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  # redis 配置
  redis:
    database: 11
    host: localhost
    port: 6379
  # Kafka 配置
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: community-consumer-group
      enable-auto-commit: true
      auto-commit-interval: 3000
  # ElasticSearch Properties 配置
  data:
    elasticsearch:
      cluster-name: community
      cluster-nodes: 127.0.0.1:9300
  # Spring taskExecutionProperties
  task:
    execution:
      pool:
        core-size: 5
        max-size: 15
        queue-capacity: 100
    # Spring taskSchedulingProperties
    scheduling:
      pool:
        size: 5
  # Spring Quartz 配置
  quartz:
    job-store-type: jdbc
    scheduler-name: communityScheduler
    properties:
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            isClustered: true
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5

mybatis:
  # 映射文件的地址
  mapper-locations: classpath*:mapper/*.xml
  # 实体类所在包名
  type-aliases-package: com.nowcoder.community.entity
  configuration:
    # 启用自动生成主键
    use-generated-keys: true
    # 启动 MySQL 中命名的下划线名字和 驼峰命名 自动匹配
    map-underscore-to-camel-case: true
    # 开启 Mybatis 二级缓存，缓存整个 namespace 内的 Mapper
    # cache-enabled: true

logging:
  # 日志级别设置
  level:
    com.nowcoder.community:
      debug
  # 文件路径。要设置文件指定名称只使用name即可
  file:
    path: D:/Java/IdeaProjects/community/log
    name:  D:/Java/IdeaProjects/community/log/community.log
  logback:
    rollingpolicy:
      max-file-size: 5MB
      file-name-pattern: D:/Java/IdeaProjects/community/log/error/log-error-%d{yyyy-MM-dd}.%i.log
      max-history: 30

# 自定义网站配置域名
community:
  path:
    domain: http://localhost:8080
    upload: D:\Java\IdeaProjects\community\src\main\resources\static\header

# 自定义 wk 命令行操作
wk:
  image:
    command: D:/Java/wkhtmltopdf/bin/wkhtmltoimage
    storage: D:/Java/IdeaProjects/community/log/wk/image